admin_portada:
    path: /
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:listar }
    
admin_evento_listar:
    path: /evento/listar
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:listar }
    
admin_evento_inscriptos:
    path: /evento/inscriptos/{id}
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:inscriptos }
 
admin_evento_borrar:
    path: /evento/borrar/{id}
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:borrar }

admin_evento_nuevo:
    path: /evento/nuevo
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:nuevo }
    
admin_evento_editar:
    path: /evento/editar/{id}
    defaults: { _controller: CursoSymfonyEventosBundle:AdminEvento:editar }
    requirements:
        id: \d+

admin_disertante_listar:
    path: /disertante/listar
    defaults: { _controller: CursoSymfonyEventosBundle:AdminDisertante:listar }
        
admin_disertante_nuevo:
    path: /disertante/nuevo
    defaults: { _controller: CursoSymfonyEventosBundle:AdminDisertante:nuevo }

admin_disertante_editar:
    path: /disertante/editar/{id}
    defaults: { _controller: CursoSymfonyEventosBundle:AdminDisertante:editar }
    requirements:
        id: \d+        
    