estatica:
    path: /sitio/{pagina}
    defaults: { _controller: CursoSymfonyEventosBundle:Default:estatica }
    
portada:
    path: /
    defaults: { _controller: CursoSymfonyEventosBundle:Default:portada }

eventos:
    path: /eventos
    defaults: { _controller: CursoSymfonyEventosBundle:Evento:eventos }