estatica:
    path: /sitio/{pagina}
    defaults: { _controller: CursoSymfonyEventosBundle:Default:estatica }
    
portada:
    path: /
    defaults: { _controller: CursoSymfonyEventosBundle:Default:portada }

eventos:
    path: /eventos
    defaults: { _controller: CursoSymfonyEventosBundle:Evento:eventos }
    
evento:
    path: /evento/{slug}
    defaults: { _controller: CursoSymfonyEventosBundle:Evento:evento }
    requirements:
        _method: GET
    
disertantes:
    path: /disertantes
    defaults: { _controller: CursoSymfonyEventosBundle:Disertante:disertantes }
    
disertante:
    path: /disertante/{id}
    defaults: { _controller: CursoSymfonyEventosBundle:Disertante:disertante }